BarberBoss/Controllers/AppointmentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BarberBoss.Models;
using Microsoft.AspNet.Identity;

namespace BarberBoss.Controllers
{
    public class AppointmentsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Appointments
        [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            var appointments = db.Appointments.Include(a => a.Barber);
            return View(appointments.ToList());
        }

        // GET: Appointments/Details/5
        [Authorize(Roles = "Admin")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Appointment appointment = db.Appointments.Find(id);
            if (appointment == null)
            {
                return HttpNotFound();
            }
            return View(appointment);
        }

        // GET: Appointments/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            ViewBag.BarberId = new SelectList(db.Barbers, "Id", "Name");
            //ViewBag.ClientId = new SelectList(db.Clients, "Id", "Name");
            return View();
        }

        // POST: Appointments/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Create([Bind(Include = "Id,StartTime,StartTimeString,BookTime,BookTimeString,IsBooked,ServiceId,EndTimeString,ClientId,BarberId")] Appointment appointment)
        {
            if (ModelState.IsValid)
            {
                db.Appointments.Add(appointment);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.BarberId = new SelectList(db.Barbers, "Id", "Name", appointment.BarberId);
            //ViewBag.ClientId = new SelectList(db.Clients, "Id", "Name", appointment.ClientId);
            return View(appointment);
        }

        // GET: Appointments/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Appointment appointment = db.Appointments.Find(id);
            if (appointment == null)
            {
                return HttpNotFound();
            }
            ViewBag.BarberId = new SelectList(db.Barbers, "Id", "Name", appointment.BarberId);
            //ViewBag.ClientId = new SelectList(db.Clients, "Id", "Name", appointment.ClientId);
            return View(appointment);
        }

        // POST: Appointments/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit([Bind(Include = "Id,StartTime,StartTimeString,BookTime,BookTimeString,IsBooked,ServiceId,EndTimeString,ClientId,BarberId")] Appointment appointment)
        {
            if (ModelState.IsValid)
            {
                db.Entry(appointment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.BarberId = new SelectList(db.Barbers, "Id", "Name", appointment.BarberId);
            //ViewBag.ClientId = new SelectList(db.Clients, "Id", "Name", appointment.ClientId);
            return View(appointment);
        }

        // GET: Appointments/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Appointment appointment = db.Appointments.Find(id);
            if (appointment == null)
            {
                return HttpNotFound();
            }
            return View(appointment);
        }

        // POST: Appointments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteConfirmed(int id)
        {
            Appointment appointment = db.Appointments.Find(id);
            db.Appointments.Remove(appointment);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        //CUSTOM VIEWS
        [HttpGet]
        [Authorize(Roles = "Admin,Client")]
        public ActionResult Calendar()
        {
            if (User.Identity.IsAuthenticated)
            {
                return View("Calendar");
            }
            return RedirectToAction("Login", "Account");
            
        }

        [HttpPost]
        [Authorize(Roles = "Admin,Client")]
        public JsonResult CreateAppointment(string startTime)
        {
            DateTime start = DateTime.Parse(startTime);
            PartialAppointment partial = new PartialAppointment();
            partial.startTime = start;
            partial.startTimeString = start.ToString("yyyy-MM-dd HH:mm:ss");
            partial.bookTime = DateTime.Now;
            partial.bookTimeString = partial.bookTime.ToString("yyyy-MM-dd HH:mm:ss");
            db.PartialAppointments.Add(partial);
            db.SaveChanges();

            return Json(partial.Id);
        }

        [HttpGet]
        [Authorize(Roles = "Admin,Client")]
        public ActionResult BookAppointment(int id)
        {
            
            var partial = db.PartialAppointments.Find(id);

            ViewBag.ServicesIds = new SelectList(db.ServiceOffers, "Id", "Title");

            return View(partial);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,Client")]
        public ActionResult BookAppointment(PartialAppointment partialAppointment)
        {
            Appointment appointment = new Appointment();
            Barber barber = db.Barbers.Find(partialAppointment.BarberId);
            

            appointment.StartTime = partialAppointment.startTime;
            appointment.StartTimeString = partialAppointment.startTime.ToString("yyyy-MM-dd HH:mm:ss");
            appointment.BookTime = DateTime.Now;
            appointment.BookTimeString = partialAppointment.bookTime.ToString("yyyy-MM-dd HH:mm:ss");
            appointment.ServiceOffer = db.ServiceOffers.Find(partialAppointment.OfferId);
            appointment.ServiceId = partialAppointment.OfferId;
            appointment.Barber = db.Barbers.Find(partialAppointment.BarberId);
            appointment.BarberId = partialAppointment.BarberId;
            appointment.ApplicationUser = db.Users.Find(User.Identity.GetUserId());
            appointment.IsBooked = true;

            barber.Appointments.Add(appointment);
            

            db.Appointments.Add(appointment);
            db.SaveChanges();
            return RedirectToAction("Calendar");
        }


        //Get JSON DATA


        [AllowAnonymous]
        public JsonResult GetAppointments()
        {
            // Get the current user's ID
            var currentUserId = User.Identity.GetUserId();

            var appointments = db.Appointments.Include(a => a.ServiceOffer).Include(b => b.Barber).Where(a => a.StartTime.CompareTo(DateTime.Now) >= 0 && a.ApplicationUser.Id == currentUserId).ToList();
            List<AppointmentDTO> list = new List<AppointmentDTO>();

            foreach (var app in appointments)
            {
                AppointmentDTO AppointmentDTO = new AppointmentDTO();
                AppointmentDTO.StartTime = app.StartTime.ToString("yyyy-MM-dd HH:mm:ss") + ".000";
                AppointmentDTO.EndTime = app.StartTime.AddMinutes(app.ServiceOffer.Duration).ToString("yyyy-MM-dd HH:mm:ss") + ".000";
                AppointmentDTO.BookTime = app.BookTime != null ? app.BookTime.ToString("yyyy-MM-dd HH:mm:ss") + ".000" : null;
                AppointmentDTO.Price = app.ServiceOffer.Price;
                AppointmentDTO.Title = app.ServiceOffer.Title;
                AppointmentDTO.IsBooked = app.IsBooked;
                AppointmentDTO.Id = app.Id;
                AppointmentDTO.BarberId = app.BarberId;
                AppointmentDTO.BarberName = app.Barber.Name;

                list.Add(AppointmentDTO);
            }

            return new JsonResult { Data = list, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }

        [AllowAnonymous]
        public JsonResult GetBarbersForService(int serviceId, long selectedTime)
        {
            //// Get the list of barbers offering the selected service
            //var barbersForService = db.Barbers
            //    .Where(barber => barber.ServicesOffered.Any(service => service.Id == serviceId))
            //    .ToList();

            //var barberList = barbersForService.Select(b => new SelectListItem
            //{
            //    Value = b.Id.ToString(),
            //    Text = b.Name
            //}).ToList();

            //return Json(barberList, JsonRequestBehavior.AllowGet);
            // Get the list of barbers offering the selected service

            DateTime selectedDateTime = DateTimeOffset.FromUnixTimeMilliseconds(selectedTime).LocalDateTime;

            var barbersForService = db.Barbers
                .Where(barber =>
                    barber.ServicesOffered.Any(service => service.Id == serviceId)
                )
                .Select(b => new
                {

BarberBoss/Controllers/ServiceOffersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BarberBoss.Models;

namespace BarberBoss.Controllers
{
    public class ServiceOffersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: ServiceOffers
        [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            return View(db.ServiceOffers.ToList());
        }

        // GET: ServiceOffers/Details/5
        [Authorize(Roles = "Admin")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ServiceOffer serviceOffer = db.ServiceOffers.Find(id);
            if (serviceOffer == null)
            {
                return HttpNotFound();
            }
            return View(serviceOffer);
        }

        // GET: ServiceOffers/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: ServiceOffers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Create(ServiceOffer serviceOffer)
        {
            if (ModelState.IsValid)
            {
                string fileName = Path.GetFileNameWithoutExtension(serviceOffer.ImageFile.FileName);
                string extension = Path.GetExtension(serviceOffer.ImageFile.FileName);

                fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;

                serviceOffer.ImagePath = "~/Pictures/OfferPictures/" + fileName;

                fileName = Path.Combine(Server.MapPath("~/Pictures/OfferPictures/"), fileName);
                serviceOffer.ImageFile.SaveAs(fileName);


                db.ServiceOffers.Add(serviceOffer);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(serviceOffer);
        }

        // GET: ServiceOffers/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ServiceOffer serviceOffer = db.ServiceOffers.Find(id);
            if (serviceOffer == null)
            {
                return HttpNotFound();
            }
            return View(serviceOffer);
        }

        // POST: ServiceOffers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(ServiceOffer serviceOffer)
        {
            if (ModelState.IsValid)
            {
                db.Entry(serviceOffer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(serviceOffer);
        }

        // GET: ServiceOffers/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ServiceOffer serviceOffer = db.ServiceOffers.Find(id);
            if (serviceOffer == null)
            {
                return HttpNotFound();
            }
            return View(serviceOffer);
        }

        // POST: ServiceOffers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteConfirmed(int id)
        {
            ServiceOffer serviceOffer = db.ServiceOffers.Find(id);
            db.ServiceOffers.Remove(serviceOffer);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BarberBoss/Views/Shared/_Layout.cshtml
@{
    ViewBag.Orange = "#FFC107";
}


<!DOCTYPE html>
<html>
<head>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" crossorigin="anonymous">


</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm position-sticky top-0" style="background-color: @ViewBag.Orange; z-index: 10">
        <div class="container">
            @Html.ActionLink("BarberBoss", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <dixv class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>

                    @*<li>@Html.ActionLink("Barbers", "Index", "Barbers", new { area = "" }, new { @class = "nav-link" })</li>*@

                    @if (User.IsInRole(BarberBoss.Models.Roles.Client) || !User.Identity.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Services", "Services", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("Book Appointment", "Calendar", "Appointments", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("My Appointments", "ClientAppointmentsList", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    }
                    @if (User.IsInRole(BarberBoss.Models.Roles.Barber))
                    {
                        //TODO Barber Details where he can add or remove a service he offers
                        <li>@Html.ActionLink("MyServices", "OfferedServices", "Barbers", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("MyAppointments", "listBarberAppointments", "Barbers", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("MyProfile", "barberProfile", "Barbers", new { area = "" }, new { @class = "nav-link" })</li>
                    }
                    @if (User.IsInRole(BarberBoss.Models.Roles.Admin))
                    {
                        <li>@Html.ActionLink("Appointments", "Index", "Appointments", new { area = "" }, new { @class = "nav-link" })</li>


                        <li>@Html.ActionLink("Barbers", "Index", "Barbers", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("Services", "Index", "ServiceOffers", new { area = "" }, new { @class = "nav-link" })</li>

                    }







                </ul>
                @Html.Partial("_LoginPartial")
            </dixv>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - BarberBoss</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>